###
GET {{host}}/admin/daily-word?page=1&size=10&sort=id,desc

###
GET {{host}}/admin/daily-word/latest
token: {{auth_token}}

###
GET {{host}}/admin/daily-word/1
token: {{auth_token}}

###
POST {{host}}/admin/daily-word
token: {{auth_token}}
Content-Type: application/x-www-form-urlencoded

words=1,3,4&wordPrimary=2&publishedAt=2022-03-01

###
DELETE {{host}}/admin/daily-word/2
token: {{auth_token}}
Content-Type: application/x-www-form-urlencoded

###

###
PUT {{host}}/admin/daily-word/1
token: {{auth_token}}
Content-Type: application/x-www-form-urlencoded

status=1
