###
GET {{host}}/admin/image?page=1&size=10&sort=id,desc&tagName=
###
GET {{host}}/admin/image?page=1&size=10&sort=id,desc&tagIds[]=6
###
GET {{host}}/admin/image/4
token: {{auth_token}}

###
POST {{host}}/admin/image/upload
token: {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="gohan.jpg"
Content-Type: image/*

< ./image/gohan.jpg
--WebAppBoundary--

> {%
client.global.set("image_id", response.body.data.id);
client.global.set("image_url", response.body.data.url);
%}

###
PUT {{host}}/admin/image/{{image_id}}
token: {{auth_token}}
Content-Type: application/json

{
  "name": "fluffy2",
  "tagIds": [6]
}

###
DELETE {{host}}/admin/image/3
token: {{auth_token}}

###
DELETE {{host}}/admin/image
token: {{auth_token}}
Content-Type: application/json

[7, 8]

