
GET {{host}}/
###
GET {{host}}/user/list

###
POST {{host}}/user/add
Content-Type: application/x-www-form-urlencoded

username=dogy&password=123&role=President

###
DELETE {{host}}/user
Content-Type: application/x-www-form-urlencoded

id=2

###
POST {{host}}/user/login
Content-Type: application/x-www-form-urlencoded

username=dogy&password=123

> {% client.global.set("auth_token", response.body.data); %}

###
GET {{host}}/user/test
token: {{auth_token}}

###
GET {{host}}/redis/value

###
GET {{host}}/admin/test?year=2022
token: {{auth_token}}
###
GET {{host}}/cache/cache-words
token: {{auth_token}}
###
GET {{host}}/cache/get-word?id=1
token: {{auth_token}}
