
GET {{host}}/
###
GET {{host}}/user/list

###
POST {{host}}/user/add
Content-Type: application/x-www-form-urlencoded

username=dogy&password=123&role=President

###
DELETE {{host}}/user
Content-Type: application/x-www-form-urlencoded

id=2

###
POST {{host}}/user/login
Content-Type: application/x-www-form-urlencoded

username=dogy&password=123
