GET {{host}}/admin/word?page=1&size=10&sort=id,desc
###
GET {{host}}/admin/word/distinct

###
POST {{host}}/admin/word
token: {{auth_token}}
Content-Type: application/x-www-form-urlencoded

word=x

###
DELETE {{host}}/admin/word/2
token: {{auth_token}}
Content-Type: application/x-www-form-urlencoded

###
PUT {{host}}/admin/word/2
token: {{auth_token}}
Content-Type: application/x-www-form-urlencoded

word=Work
